name: Cypress Tests using Cypress Docker Image

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    container: cypress/browsers:node12.18.3-chrome87-ff82
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Install NPM dependencies, cache them correctly
      - name: Intall npm dependencies
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install

      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v5.3.0
        with:
          browser: chrome